version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          no_output_timeout: 3m
          command: |
            sudo apt update
            sudo apt install -y build-essential cmake remake curl clang jq
            pip3 install -r requirements.txt --user
      - run:
          no_output_timeout: 3m
          command: |
            cd tests
            bash tests.sh